require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'HealthEnrollmentApp' do
  config = use_native_modules!
  use_react_native!(
    :path => config["reactNativePath"],
    :hermes_enabled => true
  )

  target 'HealthEnrollmentAppTests' do
    inherit! :complete
    # Pods for testing
  end

  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Add any additional configuration here if needed
      end
    end
  end
end
