name: Build iOS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Install CocoaPods
        run: |
          cd ios
          pod install
      - name: Build iOS
        run: |
          xcodebuild -workspace ios/MyProject.xcworkspace -scheme MyProject -sdk iphoneos -configuration Release archive -archivePath $PWD/build/MyProject.xcarchive
      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath $PWD/build/MyProject.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $PWD/build
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: MyProject.ipa
          path: build/*.ipa
